// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CropController from "./crop_controller"
application.register("crop", CropController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import MapController from "./map_controller"
application.register("map", MapController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ToggleThemeController from "./toggle_theme_controller"
application.register("toggle-theme", ToggleThemeController)
